-- Drop the existing database
DROP DATABASE IF EXISTS ratings_dev_db;

-- Create the database
CREATE DATABASE IF NOT EXISTS ratings_dev_db;

-- Use the database
USE ratings_dev_db;

CREATE TABLE IF NOT EXISTS user_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    search_history JSON,
    interests JSON,
    view_history JSON,
    review_history JSON,
    genres JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    profile_pic VARCHAR(255) DEFAULT 'application/web/public/Default-Profile-Picture.jpg', -- Added default profile picture path
    theme_preference ENUM('light', 'dark') DEFAULT 'light',
    user_data_id INT,  -- Foreign key linking to user_data table
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_data_id) REFERENCES user_data(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS games (
    game_id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    genre VARCHAR(100),
    tags JSON,
    platforms JSON,
    playtime_estimate INT,
    developer VARCHAR(255),
    publisher VARCHAR(255),
    game_mode ENUM('single-player', 'multiplayer', 'both'),
    release_date DATE,
    review_rating INT CHECK (review_rating BETWEEN 1 AND 10),
    cover_image VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reviews (
    review_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,  -- Foreign key to users table
    game_id INT NOT NULL,  -- Foreign key to games table
    rating INT CHECK (rating BETWEEN 1 AND 5),
    review_text TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (game_id) REFERENCES games(game_id) ON DELETE CASCADE
);

-- Populating user_data with 50 samples
INSERT INTO user_data (search_history, interests, view_history, review_history, genres) VALUES
    ('["The Witcher 3", "Cyberpunk 2077", "Hades"]', '["sports", "action"]', '["The Witcher 3"]', '["1"]', '["RPG", "Adventure"]'),
    ('["Minecraft", "League of Legends", "Dark Souls III"]', '["adventure", "strategy"]', '["Minecraft"]', '["2"]', '["Strategy", "Puzzle"]'),
    ('["Animal Crossing", "Stardew Valley"]', '["puzzle", "arcade"]', '["Animal Crossing"]', '["3"]', '["Simulation"]'),
    ('["Battlefield V", "Call of Duty: Warzone"]', '["action", "sports"]', '["Battlefield V"]', '["4"]', '["Shooter"]'),
    ('["Among Us", "Phasmophobia"]', '["arcade", "mystery"]', '["Among Us"]', '["5"]', '["Horror"]'),
    ('["Assassins Creed Odyssey", "God of War"]', '["RPG", "adventure"]', '["God of War"]', '["6"]', '["Adventure"]'),
    ('["Gran Turismo Sport", "Forza Horizon 4"]', '["racing", "arcade"]', '["Gran Turismo Sport"]', '["7"]', '["Racing"]'),
    ('["Super Mario Odyssey", "Zelda: Breath of the Wild"]', '["strategy", "sports"]', '["Super Mario Odyssey"]', '["8"]', '["Platformer"]'),
    ('["Starcraft II", "Command & Conquer"]', '["strategy", "simulation"]', '["Starcraft II"]', '["9"]', '["RTS"]'),
    ('["Doom Eternal", "Half-Life 2"]', '["action", "horror"]', '["Doom Eternal"]', '["10"]', '["Shooter"]'),
    ('["Overwatch", "Valorant"]', '["shooter", "team-based"]', '["Overwatch"]', '["11"]', '["Shooter"]'),
    ('["Red Dead Redemption 2", "Elden Ring"]', '["RPG", "adventure"]', '["Elden Ring"]', '["12"]', '["RPG", "Adventure"]'),
    ('["Celeste", "Hollow Knight"]', '["platformer", "indie"]', '["Celeste"]', '["13"]', '["Platformer"]'),
    ('["Portal 2", "The Witness"]', '["puzzle", "indie"]', '["Portal 2"]', '["14"]', '["Puzzle"]'),
    ('["Age of Empires IV", "Civilization VI"]', '["strategy", "simulation"]', '["Age of Empires IV"]', '["15"]', '["RTS"]'),
    ('["FIFA 22", "NBA 2K22"]', '["sports", "simulation"]', '["FIFA 22"]', '["16"]', '["Sports"]'),
    ('["Hades", "Rogue Legacy 2"]', '["roguelike", "indie"]', '["Hades"]', '["17"]', '["Roguelike"]'),
    ('["Cuphead", "Ori and the Blind Forest"]', '["platformer", "action"]', '["Cuphead"]', '["18"]', '["Platformer"]'),
    ('["Genshin Impact", "Tower of Fantasy"]', '["adventure", "open-world"]', '["Genshin Impact"]', '["19"]', '["Adventure"]'),
    ('["Dark Souls III", "Sekiro"]', '["action", "RPG"]', '["Dark Souls III"]', '["20"]', '["RPG"]'),
    ('["Grand Theft Auto V", "Saints Row"]', '["action", "adventure"]', '["Grand Theft Auto V"]', '["21"]', '["Action"]'),
    ('["The Sims 4", "Planet Zoo"]', '["simulation", "building"]', '["The Sims 4"]', '["22"]', '["Simulation"]'),
    ('["Dead by Daylight", "Friday the 13th"]', '["horror", "survival"]', '["Dead by Daylight"]', '["23"]', '["Horror"]'),
    ('["Rocket League", "Need for Speed Heat"]', '["racing", "sports"]', '["Rocket League"]', '["24"]', '["Racing"]'),
    ('["Far Cry 6", "Just Cause 4"]', '["action", "open-world"]', '["Far Cry 6"]', '["25"]', '["Adventure"]'),
    ('["The Elder Scrolls V: Skyrim", "Fallout 4"]', '["RPG", "open-world"]', '["Skyrim"]', '["26"]', '["RPG"]'),
    ('["The Binding of Isaac", "Enter the Gungeon"]', '["roguelike", "indie"]', '["The Binding of Isaac"]', '["27"]', '["Roguelike"]'),
    ('["Hitman 3", "Dishonored 2"]', '["stealth", "action"]', '["Hitman 3"]', '["28"]', '["Action"]'),
    ('["Apex Legends", "PUBG"]', '["battle-royale", "shooter"]', '["Apex Legends"]', '["29"]', '["Shooter"]'),
    ('["Splatoon 3", "Mario Kart 8"]', '["shooter", "arcade"]', '["Splatoon 3"]', '["30"]', '["Shooter"]'),
    ('["Valorant", "CS: GO"]', '["competitive", "shooter"]', '["Valorant"]', '["31"]', '["Shooter"]'),
    ('["EVE Online", "Star Citizen"]', '["space", "MMO"]', '["EVE Online"]', '["32"]', '["MMO"]'),
    ('["Final Fantasy XIV", "World of Warcraft"]', '["MMO", "RPG"]', '["Final Fantasy XIV"]', '["33"]', '["MMO"]'),
    ('["Hollow Knight", "Salt and Sanctuary"]', '["metroidvania", "indie"]', '["Hollow Knight"]', '["34"]', '["Metroidvania"]'),
    ('["Borderlands 3", "Destiny 2"]', '["looter-shooter", "action"]', '["Borderlands 3"]', '["35"]', '["Shooter"]'),
    ('["Animal Crossing", "Stardew Valley"]', '["simulation", "casual"]', '["Animal Crossing"]', '["36"]', '["Simulation"]'),
    ('["Call of Duty: Warzone", "Battlefield 2042"]', '["shooter", "team-based"]', '["Warzone"]', '["37"]', '["Shooter"]'),
    ('["The Division 2", "Rainbow Six Siege"]', '["tactical", "action"]', '["The Division 2"]', '["38"]', '["Tactical"]'),
    ('["Control", "Alan Wake"]', '["mystery", "adventure"]', '["Control"]', '["39"]', '["Adventure"]'),
    ('["Returnal", "Deathloop"]', '["action", "sci-fi"]', '["Returnal"]', '["40"]', '["Action"]'),
    ('["Outer Wilds", "No Mans Sky"]', '["exploration", "sci-fi"]', '["Outer Wilds"]', '["41"]', '["Adventure"]'),
    ('["Horizon Forbidden West", "Ghost of Tsushima"]', '["open-world", "RPG"]', '["Horizon Forbidden West"]', '["42"]', '["RPG"]'),
    ('["Control", "Prey"]', '["action", "sci-fi"]', '["Control"]', '["43"]', '["Adventure"]'),
    ('["Forza Horizon 5", "Gran Turismo 7"]', '["racing", "arcade"]', '["Forza Horizon 5"]', '["44"]', '["Racing"]'),
    ('["Metro Exodus", "Chernobylite"]', '["shooter", "horror"]', '["Metro Exodus"]', '["45"]', '["Shooter"]'),
    ('["Terraria", "Starbound"]', '["sandbox", "building"]', '["Terraria"]', '["46"]', '["Sandbox"]'),
    ('["Darkest Dungeon", "Slay the Spire"]', '["strategy", "indie"]', '["Darkest Dungeon"]', '["47"]', '["Strategy"]'),
    ('["XCOM 2", "Phoenix Point"]', '["strategy", "tactical"]', '["XCOM 2"]', '["48"]', '["Strategy"]'),
    ('["XCOM 2", "Phoenix Point"]', '["strategy", "tactical"]', '["XCOM 2"]', '["48"]', '["Strategy"]'),
    ('["Sea of Thieves", "Raft"]', '["exploration", "multiplayer"]', '["Sea of Thieves"]', '["49"]', '["Adventure"]'),
    ('["It Takes Two", "A Way Out"]', '["co-op", "adventure"]', '["It Takes Two"]', '["50"]', '["Adventure"]');

INSERT INTO users (name, email, password, profile_pic, theme_preference, user_data_id) VALUES
    ('Alice Smith', 'alice.smith@example.com', 'password1', 'https://picsum.photos/seed/picsum/1', 'light', 1),
    ('Bob Johnson', 'bob.johnson@example.com', 'password2', 'https://picsum.photos/seed/picsum/2', 'dark', 2),
    ('Charlie Brown', 'charlie.brown@example.com', 'password3', 'https://picsum.photos/seed/picsum/3', 'light', 3),
    ('David Wilson', 'david.wilson@example.com', 'password4', 'https://picsum.photos/seed/picsum/4', 'dark', 4),
    ('Eve Davis', 'eve.davis@example.com', 'password5', 'https://picsum.photos/seed/picsum/5', 'light', 5),
    ('Frank Miller', 'frank.miller@example.com', 'password6', 'https://picsum.photos/seed/picsum/6', 'dark', 6),
    ('Grace Lee', 'grace.lee@example.com', 'password7', 'https://picsum.photos/seed/picsum/7', 'light', 7),
    ('Henry Adams', 'henry.adams@example.com', 'password8', 'https://picsum.photos/seed/picsum/8', 'dark', 8),
    ('Ivy Green', 'ivy.green@example.com', 'password9', 'https://picsum.photos/seed/picsum/9', 'light', 9),
    ('Jack White', 'jack.white@example.com', 'password10', 'https://picsum.photos/seed/picsum/10', 'dark', 10),
    ('Karen Black', 'karen.black@example.com', 'password11', 'https://picsum.photos/seed/picsum/11', 'light', 11),
    ('Larry Blue', 'larry.blue@example.com', 'password12', 'https://picsum.photos/seed/picsum/12', 'dark', 12),
    ('Megan Pink', 'megan.pink@example.com', 'password13', 'https://picsum.photos/seed/picsum/13', 'light', 13),
    ('Nate Gold', 'nate.gold@example.com', 'password14', 'https://picsum.photos/seed/picsum/14', 'dark', 14),
    ('Olivia Gray', 'olivia.gray@example.com', 'password15', 'https://picsum.photos/seed/picsum/15', 'light', 15),
    ('Paul Silver', 'paul.silver@example.com', 'password16', 'https://picsum.photos/seed/picsum/16', 'dark', 16),
    ('Quinn White', 'quinn.white@example.com', 'password17', 'https://picsum.photos/seed/picsum/17', 'light', 17),
    ('Rachel Green', 'rachel.green@example.com', 'password18', 'https://picsum.photos/seed/picsum/18', 'dark', 18),
    ('Steve Black', 'steve.black@example.com', 'password19', 'https://picsum.photos/seed/picsum/19', 'light', 19),
    ('Tina Gold', 'tina.gold@example.com', 'password20', 'https://picsum.photos/seed/picsum/20', 'dark', 20),
    ('Uma Brown', 'uma.brown@example.com', 'password21', 'https://picsum.photos/seed/picsum/21', 'light', 21),
    ('Victor Gray', 'victor.gray@example.com', 'password22', 'https://picsum.photos/seed/picsum/22', 'dark', 22),
    ('Wendy Blue', 'wendy.blue@example.com', 'password23', 'https://picsum.photos/seed/picsum/23', 'light', 23),
    ('Xander White', 'xander.white@example.com', 'password24', 'https://picsum.photos/seed/picsum/24', 'dark', 24),
    ('Yara Green', 'yara.green@example.com', 'password25', 'https://picsum.photos/seed/picsum/25', 'light', 25),
    ('Zane Gold', 'zane.gold@example.com', 'password26', 'https://picsum.photos/seed/picsum/26', 'dark', 26),
    ('Amy Silver', 'amy.silver@example.com', 'password27', 'https://picsum.photos/seed/picsum/27', 'light', 27),
    ('Brian Red', 'brian.red@example.com', 'password28', 'https://picsum.photos/seed/picsum/28', 'dark', 28),
    ('Cindy Orange', 'cindy.orange@example.com', 'password29', 'https://picsum.photos/seed/picsum/29', 'light', 29),
    ('Derek Yellow', 'derek.yellow@example.com', 'password30', 'https://picsum.photos/seed/picsum/30', 'dark', 30),
    ('Ella Purple', 'ella.purple@example.com', 'password31', 'https://picsum.photos/seed/picsum/31', 'light', 31),
    ('Frank Cyan', 'frank.cyan@example.com', 'password32', 'https://picsum.photos/seed/picsum/32', 'dark', 32),
    ('Gina Violet', 'gina.violet@example.com', 'password33', 'https://picsum.photos/seed/picsum/33', 'light', 33),
    ('Hank Blue', 'hank.blue@example.com', 'password34', 'https://picsum.photos/seed/picsum/34', 'dark', 34),
    ('Ivy Indigo', 'ivy.indigo@example.com', 'password35', 'https://picsum.photos/seed/picsum/35', 'light', 35),
    ('Jack Crimson', 'jack.crimson@example.com', 'password36', 'https://picsum.photos/seed/picsum/36', 'dark', 36),
    ('Karen White', 'karen.white@example.com', 'password37', 'https://picsum.photos/seed/picsum/37', 'light', 37),
    ('Larry Brown', 'larry.brown@example.com', 'password38', 'https://picsum.photos/seed/picsum/38', 'dark', 38),
    ('Megan Green', 'megan.green@example.com', 'password39', 'https://picsum.photos/seed/picsum/39', 'light', 39),
    ('Nate Blue', 'nate.blue@example.com', 'password40', 'https://picsum.photos/seed/picsum/40', 'dark', 40),
    ('Olivia Red', 'olivia.red@example.com', 'password41', 'https://picsum.photos/seed/picsum/41', 'light', 41),
    ('Paul Yellow', 'paul.yellow@example.com', 'password42', 'https://picsum.photos/seed/picsum/42', 'dark', 42),
    ('Quinn Purple', 'quinn.purple@example.com', 'password43', 'https://picsum.photos/seed/picsum/43', 'light', 43),
    ('Rachel Cyan', 'rachel.cyan@example.com', 'password44', 'https://picsum.photos/seed/picsum/44', 'dark', 44),
    ('Steve Violet', 'steve.violet@example.com', 'password45', 'https://picsum.photos/seed/picsum/45', 'light', 45),
    ('Tina Indigo', 'tina.indigo@example.com', 'password46', 'https://picsum.photos/seed/picsum/46', 'dark', 46),
    ('Uma Crimson', 'uma.crimson@example.com', 'password47', 'https://picsum.photos/seed/picsum/47', 'light', 47),
    ('Victor Gold', 'victor.gold@example.com', 'password48', 'https://picsum.photos/seed/picsum/48', 'dark', 48),
    ('Wendy Silver', 'wendy.silver@example.com', 'password49', 'https://picsum.photos/seed/picsum/49', 'light', 49),
    ('Xander Orange', 'xander.orange@example.com', 'password50', 'https://picsum.photos/seed/picsum/50', 'dark', 50);

INSERT INTO games (title, description, genre, tags, platforms, playtime_estimate, developer, publisher, game_mode, release_date, review_rating, cover_image) VALUES
    ('Fortnite', 'Battle royale shooter', 'Shooter', '["battle-royale"]', '["PC", "PlayStation", "Xbox"]', 50, 'Epic Games', 'Epic Games', 'multiplayer', '2018-03-12', 8, 'https://picsum.photos/seed/picsum/1'),
    ('FIFA 21', 'Soccer simulation game', 'Sports', '["sports", "simulation"]', '["PC", "PlayStation", "Xbox"]', 40, 'EA Sports', 'Electronic Arts', 'multiplayer', '2020-10-06', 7, 'https://picsum.photos/seed/picsum/2'),
    ('Minecraft', 'Open-world sandbox', 'Sandbox', '["sandbox", "creative"]', '["PC", "PlayStation", "Xbox", "Mobile"]', 1000, 'Mojang Studios', 'Mojang Studios', 'both', '2011-11-18', 9, 'https://picsum.photos/seed/picsum/3'),
    ('The Witcher 3', 'Fantasy RPG', 'RPG', '["fantasy", "open-world"]', '["PC", "PlayStation", "Xbox"]', 150, 'CD Projekt Red', 'CD Projekt', 'single-player', '2015-05-18', 10, 'https://picsum.photos/seed/picsum/4'),
    ('Valorant', 'Tactical shooter', 'Shooter', '["tactical", "competitive"]', '["PC"]', 50, 'Riot Games', 'Riot Games', 'multiplayer', '2020-06-02', 9, 'https://picsum.photos/seed/picsum/5'),
    ('Apex Legends', 'Battle royale with characters', 'Shooter', '["battle-royale", "character-based"]', '["PC", "PlayStation", "Xbox"]', 30, 'Respawn Entertainment', 'Electronic Arts', 'multiplayer', '2019-02-04', 9, 'https://picsum.photos/seed/picsum/6'),
    ('League of Legends', 'Popular MOBA', 'Strategy', '["MOBA", "competitive"]', '["PC"]', 200, 'Riot Games', 'Riot Games', 'multiplayer', '2009-10-27', 8, 'https://picsum.photos/seed/picsum/7'),
    ('Overwatch', 'Team-based shooter', 'Shooter', '["team-based", "competitive"]', '["PC", "PlayStation", "Xbox"]', 40, 'Blizzard', 'Blizzard', 'multiplayer', '2016-05-24', 9, 'https://picsum.photos/seed/picsum/8'),
    ('Cyberpunk 2077', 'Futuristic RPG', 'RPG', '["open-world", "sci-fi"]', '["PC", "PlayStation", "Xbox"]', 100, 'CD Projekt Red', 'CD Projekt', 'single-player', '2020-12-10', 7, 'https://picsum.photos/seed/picsum/9'),
    ('Stardew Valley', 'Farming simulation', 'Simulation', '["farming", "life-simulation"]', '["PC", "PlayStation", "Xbox", "Mobile"]', 60, 'ConcernedApe', 'ConcernedApe', 'single-player', '2016-02-26', 9, 'https://picsum.photos/seed/picsum/10'),
    ('Hollow Knight', 'Dark and moody platformer', 'Platformer', '["metroidvania", "indie"]', '["PC", "PlayStation", "Xbox", "Switch"]', 50, 'Team Cherry', 'Team Cherry', 'single-player', '2017-02-24', 10, 'https://picsum.photos/seed/picsum/11'),
    ('Celeste', 'Challenging platformer', 'Platformer', '["indie", "adventure"]', '["PC", "PlayStation", "Xbox", "Switch"]', 30, 'Maddy Makes Games', 'Maddy Makes Games', 'single-player', '2018-01-25', 9, 'https://picsum.photos/seed/picsum/12'),
    ('Dark Souls III', 'Dark fantasy RPG', 'RPG', '["action", "fantasy"]', '["PC", "PlayStation", "Xbox"]', 120, 'FromSoftware', 'Bandai Namco', 'single-player', '2016-03-24', 9, 'https://picsum.photos/seed/picsum/13'),
    ('Elden Ring', 'Open-world souls-like RPG', 'RPG', '["fantasy", "open-world"]', '["PC", "PlayStation", "Xbox"]', 120, 'FromSoftware', 'Bandai Namco', 'single-player', '2022-02-25', 10, 'https://picsum.photos/seed/picsum/14'),
    ('Genshin Impact', 'Action RPG with gacha elements', 'RPG', '["open-world", "fantasy"]', '["PC", "PlayStation", "Mobile"]', 500, 'miHoYo', 'miHoYo', 'both', '2020-09-28', 8, 'https://picsum.photos/seed/picsum/15'),
    ('Rocket League', 'Soccer with cars', 'Sports', '["competitive", "arcade"]', '["PC", "PlayStation", "Xbox", "Switch"]', 200, 'Psyonix', 'Psyonix', 'multiplayer', '2015-07-07', 9, 'https://picsum.photos/seed/picsum/16'),
    ('FIFA 23', 'Latest soccer simulation', 'Sports', '["sports", "simulation"]', '["PC", "PlayStation", "Xbox"]', 100, 'EA Sports', 'Electronic Arts', 'multiplayer', '2022-09-30', 7, 'https://picsum.photos/seed/picsum/17'),
    ('Forza Horizon 5', 'Open-world racing game', 'Racing', '["open-world", "arcade"]', '["PC", "Xbox"]', 80, 'Playground Games', 'Xbox Game Studios', 'both', '2021-11-05', 9, 'https://picsum.photos/seed/picsum/18'),
    ('Gran Turismo 7', 'Realistic racing simulator', 'Racing', '["simulation", "sports"]', '["PlayStation"]', 70, 'Polyphony Digital', 'Sony Interactive', 'both', '2022-03-04', 8, 'https://picsum.photos/seed/picsum/19'),
    ('Call of Duty: Warzone', 'Battle royale shooter', 'Shooter', '["battle-royale", "action"]', '["PC", "PlayStation", "Xbox"]', 50, 'Infinity Ward', 'Activision', 'multiplayer', '2020-03-10', 8, 'https://picsum.photos/seed/picsum/20'),
    ('The Last of Us Part II', 'Emotional narrative action game', 'Adventure', '["story-driven", "action"]', '["PlayStation"]', 100, 'Naughty Dog', 'Sony Interactive', 'single-player', '2020-06-19', 10, 'https://picsum.photos/seed/picsum/21'),
    ('Ghost of Tsushima', 'Samurai open-world adventure', 'Adventure', '["open-world", "historical"]', '["PlayStation"]', 80, 'Sucker Punch Productions', 'Sony Interactive', 'single-player', '2020-07-17', 9, 'https://picsum.photos/seed/picsum/22'),
    ('Animal Crossing: New Horizons', 'Relaxing life simulation', 'Simulation', '["casual", "building"]', '["Switch"]', 200, 'Nintendo', 'Nintendo', 'single-player', '2020-03-20', 10, 'https://picsum.photos/seed/picsum/23'),
    ('Mario Kart 8 Deluxe', 'Competitive racing game', 'Racing', '["arcade", "competitive"]', '["Switch"]', 100, 'Nintendo', 'Nintendo', 'both', '2017-04-28', 9, 'https://picsum.photos/seed/picsum/24'),
    ('Zelda: Breath of the Wild', 'Open-world adventure game', 'Adventure', '["open-world", "fantasy"]', '["Switch"]', 200, 'Nintendo', 'Nintendo', 'single-player', '2017-03-03', 10, 'https://picsum.photos/seed/picsum/25'),
    ('Super Mario Odyssey', '3D platformer adventure', 'Platformer', '["platformer", "action"]', '["Switch"]', 50, 'Nintendo', 'Nintendo', 'single-player', '2017-10-27', 10, 'https://picsum.photos/seed/picsum/26'),
    ('Splatoon 3', 'Team-based ink shooter', 'Shooter', '["team-based", "multiplayer"]', '["Switch"]', 50, 'Nintendo', 'Nintendo', 'multiplayer', '2022-09-09', 9, 'https://picsum.photos/seed/picsum/27'),
    ('Fall Guys', 'Wacky battle royale platformer', 'Party', '["multiplayer", "casual"]', '["PC", "PlayStation", "Xbox", "Switch"]', 20, 'Mediatonic', 'Epic Games', 'multiplayer', '2020-08-04', 8, 'https://picsum.photos/seed/picsum/28'),
    ('Among Us', 'Social deduction party game', 'Party', '["multiplayer", "strategy"]', '["PC", "Mobile", "Switch"]', 10, 'InnerSloth', 'InnerSloth', 'multiplayer', '2018-06-15', 7, 'https://picsum.photos/seed/picsum/29'),
    ('Terraria', '2D sandbox adventure', 'Sandbox', '["building", "exploration"]', '["PC", "PlayStation", "Xbox", "Mobile"]', 100, 'Re-Logic', 'Re-Logic', 'both', '2011-05-16', 9, 'https://picsum.photos/seed/picsum/30'),
    ('No Mans Sky', 'Massive space exploration', 'Adventure', '["open-world", "sci-fi"]', '["PC", "PlayStation", "Xbox"]', 200, 'Hello Games', 'Hello Games', 'both', '2016-08-09', 8, 'https://picsum.photos/seed/picsum/31'),
    ('Metro Exodus', 'Post-apocalyptic shooter', 'Shooter', '["story-driven", "action"]', '["PC", "PlayStation", "Xbox"]', 80, '4A Games', 'Deep Silver', 'single-player', '2019-02-15', 8, 'https://picsum.photos/seed/picsum/32'),
    ('Far Cry 6', 'Open-world FPS', 'Shooter', '["action", "adventure"]', '["PC", "PlayStation", "Xbox"]', 70, 'Ubisoft', 'Ubisoft', 'single-player', '2021-10-07', 7, 'https://picsum.photos/seed/picsum/33'),
    ('Destiny 2', 'Sci-fi looter shooter', 'Shooter', '["multiplayer", "sci-fi"]', '["PC", "PlayStation", "Xbox"]', 150, 'Bungie', 'Bungie', 'multiplayer', '2017-09-06', 9, 'https://picsum.photos/seed/picsum/34'),
    ('Borderlands 3', 'Comic-style looter shooter', 'Shooter', '["action", "RPG"]', '["PC", "PlayStation", "Xbox"]', 80, 'Gearbox Software', '2K Games', 'multiplayer', '2019-09-13', 8, 'https://picsum.photos/seed/picsum/35'),
    ('XCOM 2', 'Tactical alien defense', 'Strategy', '["turn-based", "tactical"]', '["PC", "PlayStation", "Xbox"]', 60, 'Firaxis Games', '2K Games', 'single-player', '2016-02-05', 9, 'https://picsum.photos/seed/picsum/36'),
    ('Civilization VI', 'Turn-based strategy empire builder', 'Strategy', '["historical", "simulation"]', '["PC", "PlayStation", "Xbox", "Switch"]', 200, 'Firaxis Games', '2K Games', 'single-player', '2016-10-21', 10, 'https://picsum.photos/seed/picsum/37'),
    ('Planet Zoo', 'Animal park simulation', 'Simulation', '["building", "management"]', '["PC"]', 150, 'Frontier Developments', 'Frontier Developments', 'single-player', '2019-11-05', 8, 'https://picsum.photos/seed/picsum/38'),
    ('Stardew Valley', 'Charming farming simulator', 'Simulation', '["farming", "life-simulation"]', '["PC", "PlayStation", "Xbox", "Mobile"]', 100, 'ConcernedApe', 'ConcernedApe', 'single-player', '2016-02-26', 10, 'https://picsum.photos/seed/picsum/39'),
    ('Hades', 'Greek mythology roguelike', 'Roguelike', '["action", "indie"]', '["PC", "PlayStation", "Xbox", "Switch"]', 40, 'Supergiant Games', 'Supergiant Games', 'single-player', '2020-09-17', 10, 'https://picsum.photos/seed/picsum/40'),
    ('The Sims 4', 'Life simulation', 'Simulation', '["casual", "building"]', '["PC", "PlayStation", "Xbox"]', 200, 'Maxis', 'Electronic Arts', 'single-player', '2014-09-02', 8, 'https://picsum.photos/seed/picsum/41'),
    ('It Takes Two', 'Co-op adventure', 'Adventure', '["multiplayer", "co-op"]', '["PC", "PlayStation", "Xbox"]', 15, 'Hazelight Studios', 'Electronic Arts', 'multiplayer', '2021-03-26', 10, 'https://picsum.photos/seed/picsum/42'),
    ('A Way Out', 'Story-driven co-op adventure', 'Adventure', '["multiplayer", "narrative"]', '["PC", "PlayStation", "Xbox"]', 10, 'Hazelight Studios', 'Electronic Arts', 'multiplayer', '2018-03-23', 9, 'https://picsum.photos/seed/picsum/43'),
    ('Sea of Thieves', 'Pirate-themed multiplayer adventure', 'Adventure', '["open-world", "co-op"]', '["PC", "Xbox"]', 50, 'Rare', 'Xbox Game Studios', 'multiplayer', '2018-03-20', 8, 'https://picsum.photos/seed/picsum/44'),
    ('Slay the Spire', 'Deck-building roguelike', 'Strategy', '["indie", "roguelike"]', '["PC", "PlayStation", "Xbox", "Switch"]', 40, 'MegaCrit', 'MegaCrit', 'single-player', '2019-01-23', 9, 'https://picsum.photos/seed/picsum/45'),
    ('The Outer Worlds', 'Sci-fi RPG adventure', 'RPG', '["action", "story-driven"]', '["PC", "PlayStation", "Xbox", "Switch"]', 40, 'Obsidian Entertainment', 'Private Division', 'single-player', '2019-10-25', 8, 'https://picsum.photos/seed/picsum/46'),
    ('Prey', 'Psychological sci-fi thriller', 'Adventure', '["sci-fi", "horror"]', '["PC", "PlayStation", "Xbox"]', 50, 'Arkane Studios', 'Bethesda Softworks', 'single-player', '2017-05-05', 9, 'https://picsum.photos/seed/picsum/47'),
    ('Control', 'Supernatural action-adventure', 'Adventure', '["sci-fi", "story-driven"]', '["PC", "PlayStation", "Xbox"]', 60, 'Remedy Entertainment', '505 Games', 'single-player', '2019-08-27', 9, 'https://picsum.photos/seed/picsum/48'),
    ('Returnal', 'Sci-fi roguelike shooter', 'Shooter', '["action", "sci-fi"]', '["PlayStation"]', 50, 'Housemarque', 'Sony Interactive', 'single-player', '2021-04-30', 9, 'https://picsum.photos/seed/picsum/49'),
    ('Deathloop', 'Time-looping action shooter', 'Shooter', '["action", "sci-fi"]', '["PC", "PlayStation"]', 40, 'Arkane Studios', 'Bethesda Softworks', 'single-player', '2021-09-14', 10, 'https://picsum.photos/seed/picsum/50');

INSERT INTO reviews (user_id, game_id, rating, review_text) VALUES
    (1, 1, 5, 'Amazing battle royale game!'),
    (2, 2, 4, 'Good soccer simulation, but a bit repetitive.'),
    (3, 3, 5, 'Best sandbox game ever, love the creativity!'),
    (4, 4, 4, 'The Witcher 3 has an incredible story and world.'),
    (5, 5, 3, 'Valorant is fun but too sweaty for casual players.'),
    (6, 6, 5, 'Apex Legends keeps me coming back with its fast-paced action.'),
    (7, 7, 4, 'League of Legends is great but toxic players ruin it.'),
    (8, 8, 4, 'Overwatch has unique heroes but feels a bit stale now.'),
    (9, 9, 2, 'Cyberpunk 2077 had potential, but the bugs killed the vibe.'),
    (10, 10, 5, 'Stardew Valley is the perfect chill farming game.'),
    (11, 11, 5, 'Hollow Knight is a masterpiece of platforming and storytelling.'),
    (12, 12, 4, 'Celeste is hard but rewarding. Great for platformer fans!'),
    (13, 13, 5, 'Dark Souls III is brutally challenging but so satisfying.'),
    (14, 14, 5, 'Elden Ring redefines open-world RPGs. A must-play!'),
    (15, 15, 4, 'Genshin Impact has gorgeous graphics but gacha is expensive.'),
    (16, 16, 5, 'Rocket League is the perfect blend of skill and fun.'),
    (17, 17, 3, 'FIFA 23 is good but feels like the same game every year.'),
    (18, 18, 5, 'Forza Horizon 5 is an exhilarating racing experience.'),
    (19, 19, 4, 'Gran Turismo 7 is great for racing fans, but lacks variety.'),
    (20, 20, 4, 'Warzone is fun with friends but needs better updates.'),
    (21, 21, 5, 'The Last of Us Part II is emotionally gripping and unforgettable.'),
    (22, 22, 5, 'Ghost of Tsushima is a breathtaking journey through feudal Japan.'),
    (23, 23, 5, 'Animal Crossing is pure joy. Perfect for relaxation.'),
    (24, 24, 5, 'Mario Kart 8 Deluxe is endlessly fun with friends.'),
    (25, 25, 5, 'Zelda: Breath of the Wild is a game-changer for open-world games.'),
    (26, 26, 5, 'Super Mario Odyssey is pure platforming brilliance.'),
    (27, 27, 4, 'Splatoon 3 is a colorful and creative shooter.'),
    (28, 28, 3, 'Fall Guys is fun for a while but gets repetitive.'),
    (29, 29, 5, 'Among Us is the ultimate party game. Love the social deduction.'),
    (30, 30, 5, 'Terraria is packed with endless exploration and creativity.'),
    (31, 31, 4, 'No Mans Sky has improved a lot since launch.'),
    (32, 32, 4, 'Metro Exodus has a gripping story and stunning visuals.'),
    (33, 33, 3, 'Far Cry 6 is okay, but feels like more of the same.'),
    (34, 34, 4, 'Destiny 2 has great gameplay but is grind-heavy.'),
    (35, 35, 5, 'Borderlands 3 is hilarious and full of action-packed fun.'),
    (36, 36, 5, 'XCOM 2 is a fantastic strategy game with endless replayability.'),
    (37, 37, 5, 'Civilization VI is one of the best strategy games out there.'),
    (38, 38, 5, 'Planet Zoo is the ultimate animal park simulator.'),
    (39, 39, 5, 'Stardew Valley is perfect for casual gamers and farming lovers.'),
    (40, 40, 5, 'Hades has incredible gameplay and storytelling.'),
    (41, 41, 4, 'The Sims 4 is a great life sim, but the expansions are pricey.'),
    (42, 42, 5, 'It Takes Two is the best co-op game Ive ever played.'),
    (43, 43, 4, 'A Way Out is a unique and engaging co-op experience.'),
    (44, 44, 5, 'Sea of Thieves is amazing with friends, a bit empty solo.'),
    (45, 45, 5, 'Slay the Spire combines deck-building and roguelikes perfectly.'),
    (46, 46, 4, 'The Outer Worlds has great humor and fun RPG mechanics.'),
    (47, 47, 5, 'Prey is an eerie and exciting sci-fi adventure.'),
    (48, 48, 5, 'Control is a mind-bending action game with stunning visuals.'),
    (49, 49, 4, 'Returnal is thrilling but brutally difficult.'),
    (50, 50, 5, 'Deathloop is an innovative and addictive shooter.');